# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 837e008
_src_path: gh:mcsitter/project_template
pre_commit_tool: prek
project_description: Process ADNI study data with ADNIpy.
project_name: ADNIpy
project_type: package
python_version: '3.12'
typing: true
with_conventional_commits: true
