[project]
name = "adnipy"
version = "1.0.1"
description = "Process ADNI study data with ADNIpy."
authors = [
  { name = "Maximilian Cosmo Sitter", email = "msitter@smail.uni-koeln.de" },
]
license = { file = "LICENSE" }
readme = "README.rst"
requires-python = ">=3.12"
keywords = ["adnipy"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "matplotlib>=3.10.0",
  "pandas>=3.0.5",
]

[dependency-groups]
types = []
dev = [
  { include-group = "types" },
  "build",
  "bump-my-version",
  "copier",
  "mypy",
  "packaging",
  "prek",
  "pytest",
  "pytest-coverage",
  "sphinx",
  "sphinx-autobuild",
  "sphinx-rtd-theme",
  "tox",
  "twine",
  "watchdog",
]

[project.urls]
Homepage = "https://github.com/mcsitter/adnipy"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812", # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
  "CPY001", # https://docs.astral.sh/ruff/rules/missing-copyright-notice/
  "D203",   # https://docs.astral.sh/ruff/rules/incorrect-blank-line-before-class/
  "D213",   # https://docs.astral.sh/ruff/rules/multi-line-summary-second-line/
  "S311",   # https://docs.astral.sh/ruff/rules/suspicious-non-cryptographic-random-usage/
]

[tool.ruff.lint.per-file-ignores]
"scripts/*.py" = [
  "INP001", # https://docs.astral.sh/ruff/rules/implicit-namespace-package/
  "T201",   # https://docs.astral.sh/ruff/rules/print/
]
"tests/*" = ["S101"]
"docs/conf.py" = ["ERA001", "PTH100", "EXE001", "A001"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[tool.mypy]
ignore_missing_imports = true

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true

[tool.bumpversion]
current_version = "1.0.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []
allow_shell_hooks = true

[[tool.bumpversion.files]]
filename = "src/adnipy/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""
