[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adnipy"
version = "1.0.0"
description = "Process ADNI study data with adnipy."
authors = [
    { name = "Maximilian Cosmo Sitter", email = "msitter@smail.uni-koeln.de" },
]
license = { file = "LICENSE" }
readme = "README.rst"
requires-python = ">=3.12"
keywords = ["adnipy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
dependencies = ["pandas>=2.3.0", "matplotlib>=3.9.0"]
[project.optional-dependencies]
dev = [
    "packaging",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "coverage",
    "ruff",
    "mypy",
    "sphinx",
    "sphinx-rtd-theme",
    "tox",
    "build",
    "twine",
]

[project.urls]
Homepage = "https://github.com/mcsitter/adnipy"

[tool.setuptools.packages.find]
include = ["adnipy*"]

[tool.ruff.lint.per-file-ignores]
# Ignore "Module level import not at top of file" for __init__.py, since it imports submodules
"adnipy/__init__.py" = ["E402"]
"tests/*" = ["S101"]
"docs/conf.py" = ["ERA001", "PTH100", "EXE001", "A001"]
"scripts/*" = ["INP001"]

[tool.mypy]
ignore_missing_imports = true
